// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4jb-Qs9RzANq1O4f0tNqtVYVG-6bPfBo',
    appId: '1:1069282290686:web:0a3ad22bece59ba006eeaf',
    messagingSenderId: '1069282290686',
    projectId: 'entek24flutter',
    authDomain: 'entek24flutter.firebaseapp.com',
    databaseURL:
        'https://yunus-b003c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'entek24flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4jb-Qs9RzANq1O4f0tNqtVYVG-6bPfBo',
    appId: '1:1069282290686:android:0a3ad22bece59ba006eeaf',
    messagingSenderId: '1069282290686',
    projectId: 'entek24flutter',
    databaseURL:
        'https://yunus-b003c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'entek24flutter.appspot.com',
  );
}
