// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD26ackVOgKYIjyLrwuurxhc0W4a5KqB7E',
    appId: '1:1058908703904:web:a8e19b68dac2a16f0e8dc5',
    messagingSenderId: '1058908703904',
    projectId: 'yunus-b003c',
    authDomain: 'yunus-b003c.firebaseapp.com',
    databaseURL:
        'https://yunus-b003c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yunus-b003c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdEkzu6xV1EEWNmTqyl4UBA6fuEde02CI',
    appId: '1:1058908703904:android:a453da7e2dc93d3f0e8dc5',
    messagingSenderId: '1058908703904',
    projectId: 'yunus-b003c',
    databaseURL:
        'https://yunus-b003c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yunus-b003c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJH-A8orRnqR4sJ6ixjTCAB1mlftU_6-g',
    appId: '1:1058908703904:ios:2965b18966c907ee0e8dc5',
    messagingSenderId: '1058908703904',
    projectId: 'yunus-b003c',
    databaseURL:
        'https://yunus-b003c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yunus-b003c.appspot.com',
    iosBundleId: 'com.example.yunusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJH-A8orRnqR4sJ6ixjTCAB1mlftU_6-g',
    appId: '1:1058908703904:ios:fd07f136956699850e8dc5',
    messagingSenderId: '1058908703904',
    projectId: 'yunus-b003c',
    databaseURL:
        'https://yunus-b003c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yunus-b003c.appspot.com',
    iosBundleId: 'com.example.yunusApp.RunnerTests',
  );
}
